import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { HeaderContextProvider } from "./context/headerContext";
=======
import ReactQueryProvider from "./service/QueyClientProvider";

>>>>>>> 5baba83658d14a8160fb4cc34fdc285b589da764

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "Stream",
  description: "Streming App",
>>>>>>> 5baba83658d14a8160fb4cc34fdc285b589da764
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en">
      <HeaderContextProvider>
        <body className={`${inter.className} bg-neutral-950`}>{children}</body>
      </HeaderContextProvider>
=======
    <html lang="pt-br">
      <body className={inter.className}>
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
      </body>
>>>>>>> 5baba83658d14a8160fb4cc34fdc285b589da764
    </html>
  );
}
